services:
  analytics-service:
    build: .
    container_name: analytics-service
    ports:
      - "4011:4011"
    environment:
      - PORT=4011
      - NODE_ENV=development
      - DB_USER=parabellum
      - DB_PASSWORD=parabellum2025
      - DATABASE_URL=postgresql://parabellum:parabellum2025@db:5432/parabellum_Analytics?schema=public
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: analytics-service-db
    environment:
      POSTGRES_USER: parabellum
      POSTGRES_PASSWORD: parabellum2025
      POSTGRES_DB: parabellum_Analytics
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parabellum -d parabellum_Analytics"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - analytics-service_db_data:/var/lib/postgresql/data

volumes:
  analytics-service_db_data:
